### ISSUE TITLE
"KeyNotFoundException" error

### ISSUE THREAD

**Issue by KikiCS** [neurodigitaltechnologies/UnitySDK#1]
Hi, I hope you can solve my problem.
I downloaded this SDK and followed the HOW-TO instructions written inside the ReadMe.
I upload the EmptyScene and I correctly visualize the Prefab Torso. I connect AvatarVR (which is correctly detected by ND Suite) and run the scene by pressing the Play button.
I get this error while nothing moves on screen: 

> KeyNotFoundException: The given key was not present in the dictionary.

In the Console I read those errors you see in the image.
![image](https://user-images.githubusercontent.com/26849627/31430883-74a84bd8-ae72-11e7-8a14-3f3d0c49be89.png)
Probably I have to set up something in order to connect AvatarVR to Unity; I'm just a beginner with this software so I'm not sure.
Thank you in advance for your help!

**Comment by PinoNeurodigital** [comment]
Hello @KikiCS ,
You have to copy the <b>NDAPI_x64.dll</b> that you can find inside the "Boxed" project and paste it in your project. Your project directory should look like this:

![projectdirectory](https://user-images.githubusercontent.com/28859044/31442195-de157640-ae95-11e7-9152-37c854433271.PNG)

Furthermore, if you compile your project for <b>Windows</b>, you should include this dll in your <b>Plugins</b> directory too. <b>PostBuildDLL.cs</b> will copy it to your application directory automatically. You can copy it manually too.
It should look like this:

![example](https://user-images.githubusercontent.com/28859044/31442439-c2c3751c-ae96-11e7-9ad7-6ab61a81bb85.PNG)

Hope it helps!

**Comment by KikiCS** [comment]
Thank you! It worked!
